### ISSUE TITLE
build的时候报NPE

### ISSUE THREAD

**Issue by yangchendev** [iReaderAndroid/X2C#1]
Caused by: java.lang.NullPointerException
	at com.zhangyue.we.anoprocesser.xml.LayoutMgr.getRFile(LayoutMgr.java:206)
	at com.zhangyue.we.anoprocesser.xml.LayoutMgr.getR(LayoutMgr.java:170)
	at com.zhangyue.we.anoprocesser.xml.LayoutMgr.setFiler(LayoutMgr.java:55)
	at com.zhangyue.we.anoprocesser.XmlProcesser.init(XmlProcesser.java:35)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1039)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1180)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)

**Comment by chengweidev** [comment]
重新拉下代码，就好了

**Comment by jaysonShao** [comment]
还是在报错，是不是还要配置其他的（我刚刚拉了最新的代码）

**Comment by longkehuawei** [comment]
还是在报错，是不是还要配置其他的（我刚刚拉了最新的代码）

**Comment by dbeqiraj** [comment]
I got this error when I upgraded from AGP7 to AGP. I added the `namespace` in `build.gradle`  while removing the `package` attribute from `AndroidManifest`.

The solution was to keep the `package` attribute in the Manifest.
