### ISSUE TITLE
NoSuchMethodError: No static method metafactory

### ISSUE THREAD

**Issue by ShaoLongFei** [iReaderAndroid/X2C#76]
java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
at androidx.core.view.ViewCompat.<clinit>(ViewCompat.java:2852)
at androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(ViewCompat.java:2534)
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:947)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
at com.zhangyue.we.x2c.X2C.setContentView(X2C.java:31)

------------------------------------------------------------------------
使用的 gradle 是 4.1.3
compileSdkVersion 32
targetSdkVersion 32

**Comment by ShaoLongFei** [comment]
抱歉，此问题与 X2C 无关
